debug: false

http_timeout: 60
timezone: "Asia/Tokyo"
standard_date_format: "%Y/%m/%d"

paths:
  csv_format: "../docs/csv/{season}_allmatch_result-ACL_GL.csv"
  timestamp_file: "../docs/csv/csv_timestamp.csv"

urls:
  source_url_format: "https://soccer.yahoo.co.jp/jleague/category/acl/schedule/31194/{}/"

section_ids:
  - "11"
  - "21"
  - "31"
  - "42"
  - "52"
  - "62"
