debug: false
season: 2026

http_timeout: 60
timezone: "Asia/Tokyo"
date_format: "%Y%m%d"
standard_date_format: "%Y/%m/%d"
jleague_date_format: "%Y年%m月%d日"

paths:
  csv_format: "../docs/csv/{season}_allmatch_result-{competition}.csv"
  timestamp_file: "../docs/csv/csv_timestamp.csv"
  season_map_file: "../docs/json/season_map.json"

urls:
  source_url_format: "https://www.jleague.jp/match/section/{}/{}/"
  standing_url_format: "https://www.jleague.jp/standings/{}/"
